[
	uuid(47A20781-26AD-465F-BDA9-AC59CEA74B69),
	version(1.0),
	helpstring("ComTestLibrary")
]
library ComTestLibrary
{
	importlib("STDOLE2.TLB");

	[
		odl,
		uuid(1B31B683-F0AA-4E71-8F50-F2D2E5E9E210),
		dual,
		oleautomation,
		nonextensible,
		helpstring("ComTestLibrary"),
		object,
	]
	interface IComTest : IDispatch
	{
		[
			id(1),
			helpstring("ComTestMethod")
		]
		HRESULT ComTestMethod(
			[in] double radius,
			[in] BSTR comment,
			[out, retval] double* ReturnVal);
	};

	[
		uuid(71AD0B2F-E5D0-4272-A4FD-18F707D5E0D6),
		helpstring("ComTest")
	]
	coclass ComTest
	{
		[default] interface IComTest;
	};
}